#!/usr/bin/env python3

import os
import time
import subprocess
from datetime import datetime

# ─── CONFIGURATION ────────────────────────────────────────────────────────────

# Absolute path to your local repo clone (on Actions it's the repo root)
REPO_DIR = "auto-push/"       # or "." if you’re already in the repo root

# File inside the repo you want to update each run
TARGET_FILE = "file.txt"

# Branch you want to push to
BRANCH = "main"

# Remote name (usually "origin")
REMOTE = "origin"

# Commit message prefix
COMMIT_PREFIX = "Automated update"

# ─── END CONFIGURATION ────────────────────────────────────────────────────────

COUNT = 0  # Initialize a counter for the number of updates

def counter():
    """Increment the counter and return the current value."""
    global COUNT
    COUNT += 1
    return COUNT

def run_cmd(cmd, **kwargs):
    """Run a shell command and raise if it fails."""
    print(f"> {' '.join(cmd)}")
    subprocess.run(cmd, check=True, **kwargs)

def configure_git_identity():
    """Set a valid author so git commit won't fail."""
    run_cmd(["git", "config", "--global", "user.name",  "kingsleyesisi"])
    run_cmd(["git", "config", "--global", "user.email", "kingsleyesisi@outlook.com"])

def setup_remote_with_token():
    """Reconfigure the 'origin' remote to include your PAT for authentication."""
    token = os.getenv("TOKEN")
    if not token:
        raise RuntimeError("❌  Please set the TOKEN environment variable in your workflow/secrets.")
    repo_slug = "kingsleyesisi/auto-push"
    auth_url = f"https://{token}@github.com/{repo_slug}.git"
    run_cmd(["git", "remote", "set-url", REMOTE, auth_url])

def modify_file():
    """Ensure the file exists and append a timestamp line to the file."""
    path = os.path.join(REPO_DIR, TARGET_FILE)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%SZ")
    with open(path, "a") as f:
        f.write(f"No. ({counter()}) This is an autogenerated line. Updated at {now}\n")

def commit_and_push():
    """Stage the change, commit with a timestamped message, and push."""
    run_cmd(["git", "add", TARGET_FILE], cwd=REPO_DIR)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%SZ")
    msg = f"{COMMIT_PREFIX} {now}"
    run_cmd(["git", "commit", "-m", msg], cwd=REPO_DIR)
    run_cmd(["git", "push", REMOTE, BRANCH], cwd=REPO_DIR)

def main_loop():
    """Infinite loop: configure → modify → commit → push → sleep."""
    # Ensure git has an author
    configure_git_identity()

    # Enter repo dir and set up the authenticated remote
    os.chdir(REPO_DIR)
    setup_remote_with_token()
    print("✅  Repo ready—starting loop (Ctrl‑C to stop).")

    while True:
        try:
            modify_file()
            commit_and_push()
            print(f"[{datetime.now().isoformat()}] ✔️  Pushed update #{COUNT}")
        except Exception as e:
            print(f"⚠️  Error during update: {e}")
        # Sleep for 2 minutes (120 seconds)
        time.sleep(2 * 60)

if __name__ == "__main__":
    main_loop()
