name: Auto‑Run Script

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}        # <— inject your secret here
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git author
        run: |
          git config --global user.name "kingsleyesisi"
          git config --global user.email "kingsleyesisi@outlook.com"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run auto_push.py
        run: python auto_push.py
