name: Auto‑Run Script

# Only run on a schedule, not on pushes or PRs
on:
  workflow_dispatch:     # <- Manual trigger
  schedule:
    - cron: '*/2 * * * *'
    
# Give the workflow permission to push commits
permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install any dependencies (if needed)
      - name: Install dependencies
        run: |
          # e.g. if you need requests or others:
          # pip install -r requirements.txt
          :

      # 4) Run your script
      - name: Run auto_push.py
        # GITHUB_TOKEN is automatically provided by GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python path/to/auto_push.py
