# .github/workflows/auto_run.yml

name: Auto-push Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run auto_push.py
        run: python auto_push.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
