name: following my followers
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 00 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AUTO_PUSH

    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN:    ${{ secrets.TOKEN }}
      GITHUB_EMAIL:    ${{ secrets.EMAIL }}

    steps:
      - uses: actions/checkout@v3
        with:
          # need write access to push
          persist-credentials: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run following_my_followers.py with arguments
        run: |
          python following_my_followers.py -m "${GITHUB_USERNAME}" -t "${GITHUB_TOKEN}"

      - name: Commit & Push updates
        run: |
          # 1. Ensure .ENV is ignored
          echo ".ENV" >> .gitignore

          # 2. Configure git author from env
          git config user.name  "${GITHUB_USERNAME}"
          git config user.email "${GITHUB_EMAIL}"

          # 3. Stage everything, then un-stage .env
          git add .
          git reset HEAD .emv

          # 4. Only commit if there is something new
          if ! git diff --cached --quiet; then
            git commit -m "chore: update following list"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          # ensure push can authenticate
          GIT_ASKPASS: /bin/true
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
