name: Follow random users

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 00 * * *'  # Every day at midnight

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AUTO_PUSH

    env:
      GITHUB_USERNAME: ${{ vars.USERNAME }}
      GITHUB_TOKEN:    ${{ vars.TOKEN }}
      GITHUB_EMAIL:    ${{ vars.EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file (in-runner only)
        run: |
          echo "GITHUB_USERNAME=${GITHUB_USERNAME}" > .env
          echo "GITHUB_TOKEN=${GITHUB_TOKEN}"   >> .env
          echo "GITHUB_EMAIL=${GITHUB_EMAIL}"   >> .env

      - name: Get random users
        run: python get_random_users.py

      - name: Run following_my_followers.py with arguments
        run: |
          python following_my_followers.py -m "${GITHUB_USERNAME}" -t "${GITHUB_TOKEN}"

      - name: Sleep before pushing
        run: sleep 120

      - name: Commit & Push
        run: |
          # 1. Ensure .env stays untracked
          echo ".env" >> .gitignore
          git reset HEAD .env || true

          # 2. Configure git author
          git config user.name  "${GITHUB_USERNAME}"
          git config user.email "${GITHUB_EMAIL}"

          # 3. Stage everything except .env
          git add .
          git reset .env

          # 4. Commit & push if changes exist
          if ! git diff --cached --quiet; then
            git commit -m "chore: update following list"
            git pull --rebase origin main
            git push
          else
            echo "No changes to commit."
          fi
