name: Follow random users

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 00 * * *'  # Every day at midnight

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AUTO_PUSH

    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      GITHUB_EMAIL: ${{ secrets.EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file (in-runner only)
        run: |
          echo "GITHUB_USERNAME=${GITHUB_USERNAME}" > .env
          echo "GITHUB_TOKEN=${GITHUB_TOKEN}"   >> .env
          echo "GITHUB_EMAIL=${GITHUB_EMAIL}"   >> .env

      - name: Get random users
        run: python get_random_users.py
        
      - name: Run following_my_followers.py with arguments
        run: |
          python following_my_followers.py -m "${GITHUB_USERNAME}" -t "${GITHUB_TOKEN}"

      # Optional: Wait 2 minutes before pushing
      - name: Sleep before pushing
        run: sleep 120

      - name: Commit & Push
        run: |
          git config user.name "${GITHUB_USERNAME}"
          git config user.email "${GITHUB_EMAIL}"
          git add .
          git diff --cached --quiet || ( git commit -m "Update following" && git push )
